[workspace]
members = [
    "node",
    "client",
    "ledger-types",
    "ledger-transport",
]

resolver = "2"

[workspace.dependencies]
clap = "4.4"
k256 = "0.13"
names = "0.14"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
hex = "0.4"